// <auto-generated />
namespace GraphMapper.ApplicationDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Latest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Latest));
        
        string IMigrationMetadata.Id
        {
            get { return "201406301852286_Latest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
