//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphMapper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphMapper.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Colors/.
        /// </summary>
        internal static string ColorFilePath {
            get {
                return ResourceManager.GetString("ColorFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidFilledBox.
        /// </summary>
        internal static string ColorImageShortName {
            get {
                return ResourceManager.GetString("ColorImageShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png.
        /// </summary>
        internal static string ColorImageTypeExtension {
            get {
                return ResourceManager.GetString("ColorImageTypeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string DefaultFileExtensionSeparator {
            get {
                return ResourceManager.GetString("DefaultFileExtensionSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidFilledBox.
        /// </summary>
        internal static string DefaultImageShortName {
            get {
                return ResourceManager.GetString("DefaultImageShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png.
        /// </summary>
        internal static string DefaultImageTypeExtension {
            get {
                return ResourceManager.GetString("DefaultImageTypeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string DefaultShapeHeight {
            get {
                return ResourceManager.GetString("DefaultShapeHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string DefaultShapeWidth {
            get {
                return ResourceManager.GetString("DefaultShapeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Shapes/.
        /// </summary>
        internal static string ImageFilePath {
            get {
                return ResourceManager.GetString("ImageFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/TempColors/.
        /// </summary>
        internal static string TempColorFilePath {
            get {
                return ResourceManager.GetString("TempColorFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/TempShapes/.
        /// </summary>
        internal static string TempImageFilePath {
            get {
                return ResourceManager.GetString("TempImageFilePath", resourceCulture);
            }
        }
    }
}
